Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/caihong/HiFi.conf"
	Comment "OnePlus Pad 2 speaker playback"
}

FixedBootSequence [
	cset "name='SECONDARY_TDM_RX_0 Audio Mixer MultiMedia1' off,off"
]
