SectionVerb {
	Value {
		TQ "HiFi"
	}
	# ACP probes the PCM after selecting the verb, before enabling a device.
	EnableSequence [
		cset "name='SECONDARY_TDM_RX_0 Audio Mixer MultiMedia1' on,on"
	]
	DisableSequence [
		disdevall ""
		cset "name='SECONDARY_TDM_RX_0 Audio Mixer MultiMedia1' off,off"
	]
}

SectionDevice."Speaker" {
	Comment "Internal speakers"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackRate 48000
		PlaybackChannels 2
		PlaybackMixer "hw:${CardId}"
		PlaybackMixerElem "Speaker"
		PlaybackVolume "name='Speaker Playback Volume'"
	}
}
